/**
 * Make an img2threejs factory shippable.
 *
 * Raw generator output is not: a quarter of it is spec JSON written onto every
 * node's `userData`, which would reach the browser, and its internals assume a
 * looser tsconfig than this repo's. Stripping the provenance and marking the
 * file generated keeps the typed import site as the place safety is enforced.
 *
 * Idempotent — safe to re-run after every regeneration.
 */

export const MARKER = "// @ts-nocheck";

export const HEADER = `${MARKER}
// GENERATED by img2threejs, normalized by plugins/asset-pipeline/skills/image-to-threejs.
// Do not edit: re-run the generator, then normalize_factory.mjs. Consume it only
// through its exported factory functions, which are typed at the call site.
`;

/**
 * Remove whole `<node>.userData.<prop> = {...};` lines.
 *
 * The generator emits each on a single line, so slicing by line is exact and
 * avoids brace-matching a few kB of inlined JSON.
 */
export function dropUserDataAssignment(source: string, prop: string): string {
  const marker = `.userData.${prop} = `;
  const out: string[] = [];
  let cursor = 0;

  for (;;) {
    const hit = source.indexOf(marker, cursor);
    if (hit === -1) break;
    const lineStart = source.lastIndexOf("\n", hit) + 1;
    const lineEnd = source.indexOf("\n", hit);
    if (lineEnd === -1) break;
    out.push(source.slice(cursor, lineStart));
    cursor = lineEnd + 1;
  }

  out.push(source.slice(cursor));
  return out.join("");
}

export function normalizeFactory(source: string, keepActionProfile = false): string {
  let out = dropUserDataAssignment(source, "sculptComponent");
  if (!keepActionProfile) out = dropUserDataAssignment(out, "actionProfile");
  // The header starts with MARKER, so a second pass is a no-op.
  return out.startsWith(MARKER) ? out : HEADER + out;
}
