packages:
  - apps/*
  - packages/*

catalog:
  "@kyh/eslint-config": ^1.1.11
  "@kyh/prettier-config": ^1.1.11
  "@kyh/tsconfig": ^1.1.11
  "@tanstack/react-query": ^5.90.16
  "@trpc/client": ^11.8.1
  "@trpc/server": ^11.8.1
  "@trpc/tanstack-react-query": ^11.8.1
  "@types/node": ^24.10.4
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  eslint: ^9.39.2
  next: ^16.1.1
  prettier: ^3.7.4
  react: ^19.2.3
  react-dom: ^19.2.3
  superjson: ^2.2.6
  typescript: ^5.9.3
  vite: ^7.3.0
  zod: ^4.3.4

linkWorkspacePackages: true

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
