#!/usr/bin/env -S uv run --python 3.12 --script
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Make an img2threejs factory shippable in this repo.

Raw generator output is not: a quarter of it is spec JSON written onto every
node's `userData`, which reaches the browser, and its internals assume a looser
tsconfig than ours. This strips the provenance and marks the file generated so
the typed import site stays the place safety is enforced.

Idempotent — re-run after every regeneration.

    uv run normalize_factory.py src/model/chest-factory.generated.ts
    uv run normalize_factory.py src/model/*.generated.ts --keep-action-profile
    uv run normalize_factory.py --selftest
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HEADER = """// @ts-nocheck
// GENERATED by img2threejs, normalized by plugins/asset-pipeline/skills/image-to-threejs.
// Do not edit: re-run the generator, then normalize_factory.py. Consume it only
// through its exported factory functions, which are typed at the call site.
"""

MARKER = "// @ts-nocheck"


def drop_userdata_assignment(source: str, prop: str) -> str:
    """Remove whole `<node>.userData.<prop> = {...};` lines.

    The generator emits each on a single line, so line-slicing is exact and
    avoids trying to brace-match a few kB of inlined JSON.
    """
    marker = f".userData.{prop} = "
    out: list[str] = []
    cursor = 0
    while True:
        hit = source.find(marker, cursor)
        if hit == -1:
            break
        line_start = source.rfind("\n", 0, hit) + 1
        line_end = source.find("\n", hit)
        if line_end == -1:
            break
        out.append(source[cursor:line_start])
        cursor = line_end + 1
    out.append(source[cursor:])
    return "".join(out)


def normalize(source: str, keep_action_profile: bool = False) -> str:
    out = drop_userdata_assignment(source, "sculptComponent")
    if not keep_action_profile:
        out = drop_userdata_assignment(out, "actionProfile")
    if not out.startswith(MARKER):
        out = HEADER + out
    return out


def selftest() -> int:
    sample = (
        "import * as THREE from 'three';\n"
        '  node_a.userData.sculptComponent = {"id": "a", "big": "payload"};\n'
        '  node_a.userData.actionProfile = {"pivot": {}};\n'
        "  node_a.name = 'keep me';\n"
    )
    once = normalize(sample)
    assert "sculptComponent" not in once, "sculptComponent survived"
    assert "actionProfile" not in once, "actionProfile survived"
    assert "keep me" in once, "dropped an unrelated line"
    assert once.startswith(MARKER), "missing generated marker"
    assert normalize(once) == once, "not idempotent"

    kept = normalize(sample, keep_action_profile=True)
    assert "actionProfile" in kept, "--keep-action-profile did not keep it"
    assert "sculptComponent" not in kept, "sculptComponent survived"

    # A file with no assignments must come back unchanged apart from the header.
    plain = "const x = 1;\n"
    assert normalize(plain) == HEADER + plain
    print("selftest ok")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("files", nargs="*", type=Path)
    ap.add_argument(
        "--keep-action-profile",
        action="store_true",
        help="keep userData.actionProfile (colliders, fracture groups) for runtime reads",
    )
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        return selftest()
    if not args.files:
        ap.error("pass at least one generated factory, or --selftest")

    failed = False
    for path in args.files:
        if not path.exists():
            sys.stderr.write(f"missing: {path}\n")
            failed = True
            continue
        before = path.read_text()
        after = normalize(before, args.keep_action_profile)
        path.write_text(after)
        saved = len(before) - len(after)
        pct = (100 * saved / len(before)) if before else 0
        print(
            f"normalized {path}: {len(before) / 1024:.1f}KB -> {len(after) / 1024:.1f}KB (-{pct:.1f}%)"
        )
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
