// Typed access to the traced Sunnyside example scene (public/assets/map.json,
// generated by tools/trace-room.mjs) plus the gameplay classification of its
// tile indices: which cells walk, till, fish, and collide.

export type TracedTileLayer = {
  name: string;
  w: number;
  h: number;
  // -1 = empty; else atlas index | flipX<<20 | flipY<<21 | rotate<<22
  grid: number[];
};

export type TracedSprite = {
  layer: string;
  sprite: string;
  x: number;
  y: number;
  sx: number;
  sy: number;
  speed: number;
};

export type DecoDef = {
  frames: number;
  fw: number;
  fh: number;
  ox: number;
  oy: number;
  fps: number;
};

export type TracedMap = {
  w: number;
  h: number;
  tileLayers: TracedTileLayer[];
  sprites: TracedSprite[];
  deco: Record<string, DecoDef>;
  animations: number[][];
  animationFps: number;
};

export const tileIndex = (v: number): number => v & 0xfffff;
export const tileFlipX = (v: number): boolean => ((v >> 20) & 1) === 1;
export const tileFlipY = (v: number): boolean => ((v >> 21) & 1) === 1;

function isNumberArray(v: unknown): v is number[] {
  return Array.isArray(v) && v.every((n) => typeof n === "number");
}

// Narrow the fetched JSON. The file is produced by our own tool, so checks are
// structural rather than exhaustive.
export function parseTracedMap(v: unknown): TracedMap {
  if (typeof v !== "object" || v === null) throw new Error("map.json: not an object");
  const o = v as Record<string, unknown>;
  const w = o["w"];
  const h = o["h"];
  if (typeof w !== "number" || typeof h !== "number") throw new Error("map.json: bad size");
  const tileLayers: TracedTileLayer[] = [];
  if (!Array.isArray(o["tileLayers"])) throw new Error("map.json: bad tileLayers");
  for (const l of o["tileLayers"]) {
    const lo = l as Record<string, unknown>;
    if (typeof lo["name"] !== "string" || !isNumberArray(lo["grid"]))
      throw new Error("map.json: bad layer");
    tileLayers.push({ name: lo["name"], w, h, grid: lo["grid"] });
  }
  const sprites: TracedSprite[] = [];
  if (!Array.isArray(o["sprites"])) throw new Error("map.json: bad sprites");
  for (const s of o["sprites"]) {
    const so = s as Record<string, unknown>;
    if (typeof so["sprite"] !== "string" || typeof so["x"] !== "number") continue;
    sprites.push({
      layer: typeof so["layer"] === "string" ? so["layer"] : "Assets_1",
      sprite: so["sprite"],
      x: so["x"],
      y: typeof so["y"] === "number" ? so["y"] : 0,
      sx: typeof so["sx"] === "number" ? so["sx"] : 1,
      sy: typeof so["sy"] === "number" ? so["sy"] : 1,
      speed: typeof so["speed"] === "number" ? so["speed"] : 1,
    });
  }
  const deco: Record<string, DecoDef> = {};
  const decoRaw = o["deco"];
  if (typeof decoRaw === "object" && decoRaw !== null) {
    for (const [k, d] of Object.entries(decoRaw)) {
      const dd = d as Record<string, unknown>;
      deco[k] = {
        frames: typeof dd["frames"] === "number" ? dd["frames"] : 1,
        fw: typeof dd["fw"] === "number" ? dd["fw"] : 16,
        fh: typeof dd["fh"] === "number" ? dd["fh"] : 16,
        ox: typeof dd["ox"] === "number" ? dd["ox"] : 0,
        oy: typeof dd["oy"] === "number" ? dd["oy"] : 0,
        fps: typeof dd["fps"] === "number" ? dd["fps"] : 8,
      };
    }
  }
  const animations = Array.isArray(o["animations"]) ? o["animations"].filter(isNumberArray) : [];
  const animationFps = typeof o["animationFps"] === "number" ? o["animationFps"] : 5;
  return { w, h, tileLayers, sprites, deco, animations, animationFps };
}

export function layerByName(map: TracedMap, name: string): TracedTileLayer | null {
  return map.tileLayers.find((l) => l.name === name) ?? null;
}

// ---------------------------------------------------------------- semantics

// Land-layer classification. Anything used-but-unlisted defaults to solid
// ground (cliff), which fails safe: you can't walk into un-vetted terrain.
const LAND_GRASS = new Set([
  66, 129, 130, 131, 132, 133, 134, 193, 194, 195, 196, 197, 198, 200, 257, 258, 259, 260, 261, 262,
  263, 326, 327, 329, 330, 332, 471, 472, 473, 474, 475, 477, 513, 534, 536, 537, 538, 539, 540,
  2123, 2124, 2125,
]);
const LAND_SAND = new Set([69, 71, 72, 73, 341]);
// the dark excavated mining yard (bottom-left) — walkable, not tillable
const LAND_DIRT = new Set([
  1803, 1804, 1867, 1868, 1929, 1930, 1931, 1932, 1994, 1995, 2058, 2059, 2060, 2061,
]);
// river / waterfall / sparkle overlays drawn on the land layer
const LAND_WATER = new Set([211, 212, 215, 478, 542, 543, 544, 545]);

// Paths are walkable overrides (bridges, stairs, ladders, doorways) except
// the structural posts that hold bridges up.
const PATH_SOLID = new Set([101, 165, 359, 361]);

// Free-standing solid props on the decoration layers (fences, rocks, graves,
// furniture). Everything else there is walk-over dressing.
const DECO_SOLID = new Set([
  // wooden + stone fences, gates, hedges
  38, 39, 113, 114, 166, 167, 170, 173, 174, 175, 108, 109, 110, 111, 177, 178,
  // trunks, stumps, big bushes & berry bushes, potted trees
  103, 104, 106, 229, 231, 232, 233, 296, 305, 306, 307, 308, 351, 352, 369, 433, 499, 500, 701,
  241, 242, 372,
  // rocks, ore boulders, gravestones, statues
  236, 287, 288, 289, 290, 300, 301, 1003, 1004, 1005, 1006, 1067, 1068, 1069, 1070, 1071, 1521,
  1522, 1523, 1524, 1525, 1526, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1777, 1778, 1779, 1780,
  1781, 1782, 1841, 1842, 1843, 1844, 1845, 1846, 1907, 1908, 1909, 1910, 1971, 1972, 1973, 1974,
  2163, 2164, 1324, 1325,
  // crates, barrels, jars, furniture, dummies, anvils, fountains
  613, 614, 615, 616, 648, 650, 677, 678, 679, 680, 684, 685, 846, 847, 861, 862, 863, 875, 876,
  878, 879, 882, 919, 920, 936, 988, 1010, 1061, 1062, 1063, 1064, 1138, 1260, 1261, 1265, 1266,
  1267, 1268, 1330, 1359, 1376, 1377, 1378, 1388, 1389, 1423, 2228, 2230, 2279, 2343, 797, 798, 799,
  1131, 1132, 1133, 1134, 1135, 1248, 1249, 1250,
]);

export const CELL = {
  void: 0, // open sea / sky — solid, fishable
  grass: 1, // walk + till
  sand: 2, // walk
  dirt: 3, // walk (mining yard, paths)
  water: 4, // river/sea visible — solid, fishable
  solid: 5, // cliff/building/fence — static collision
} as const;
export type Cell = (typeof CELL)[keyof typeof CELL];

// The farm field on the top-left plateau: traced crop dressing is suppressed
// here and the plot tiles till like grass.
export const FIELD_RECT = { x0: 9, y0: 6, x1: 21, y1: 11 } as const;
export const inField = (tx: number, ty: number): boolean =>
  tx >= FIELD_RECT.x0 && tx <= FIELD_RECT.x1 && ty >= FIELD_RECT.y0 && ty <= FIELD_RECT.y1;

export type Semantics = { kind: Uint8Array };

// Collapse the painted layers into one gameplay cell kind per tile.
export function buildSemantics(map: TracedMap): Semantics {
  const { w, h } = map;
  const kind = new Uint8Array(w * h).fill(CELL.void);
  const sea = layerByName(map, "sea");
  const land = layerByName(map, "land");
  const paths = layerByName(map, "paths");
  const deco1 = layerByName(map, "decoration_01");
  const deco2 = layerByName(map, "decoration_02");
  const forest = layerByName(map, "forest");
  const building = layerByName(map, "building");
  const walls = layerByName(map, "walls");
  const unknownLand = new Set<number>();

  for (let i = 0; i < w * h; i++) {
    if (sea && sea.grid[i] !== undefined && (sea.grid[i] ?? -1) >= 0) kind[i] = CELL.void;
    const lv = land?.grid[i] ?? -1;
    if (lv >= 0) {
      const li = tileIndex(lv);
      if (LAND_GRASS.has(li)) kind[i] = CELL.grass;
      else if (LAND_SAND.has(li)) kind[i] = CELL.sand;
      else if (LAND_DIRT.has(li)) kind[i] = CELL.dirt;
      else if (LAND_WATER.has(li)) kind[i] = CELL.water;
      else {
        kind[i] = CELL.solid;
        unknownLand.add(li);
      }
    }
    // walkable overrides: bridges, stairs, doorways, dirt paths
    const pv = paths?.grid[i] ?? -1;
    if (pv >= 0) kind[i] = PATH_SOLID.has(tileIndex(pv)) ? CELL.solid : CELL.dirt;
    // field plots till like grass
    const tx = i % w;
    const ty = (i / w) | 0;
    if (inField(tx, ty) && kind[i] !== CELL.solid) kind[i] = CELL.grass;
    // solid structures override everything
    if ((building?.grid[i] ?? -1) >= 0 || (walls?.grid[i] ?? -1) >= 0) kind[i] = CELL.solid;
    if ((forest?.grid[i] ?? -1) >= 0) kind[i] = CELL.solid;
    for (const d of [deco1, deco2]) {
      const dv = d?.grid[i] ?? -1;
      if (dv >= 0 && DECO_SOLID.has(tileIndex(dv)) && !inField(tx, ty)) kind[i] = CELL.solid;
    }
  }
  if (unknownLand.size > 0)
    console.warn(`traced: ${unknownLand.size} unclassified land tile indices treated as solid:`, [
      ...unknownLand,
    ]);
  return { kind };
}

// Solid props on decoration layers that should y-sort against the player
// (fences, graves, rocks) rather than render under everything.
export function isDecoSolidIndex(i: number): boolean {
  return DECO_SOLID.has(i);
}
