#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
from __future__ import annotations

import argparse
import shlex
import subprocess
from pathlib import Path


SKILL_DIR = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = SKILL_DIR / "scripts"


def run(cmd: list[str]) -> None:
    print("$", " ".join(shlex.quote(part) for part in cmd))
    subprocess.run(cmd, check=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the animated spritesheet salvage pipeline from generation or from an existing sheet."
    )
    parser.add_argument("--work-dir", type=Path, required=True, help="Output working directory for this run.")

    generation = parser.add_argument_group("Generation inputs")
    generation.add_argument("--reference", type=Path, help="Primary reference image for generation.")
    generation.add_argument("--guide", type=Path, help="Sheet guide image, e.g. alternating-pixel 512x1280 PNG.")
    generation.add_argument("--prompt-file", type=Path, help="Prompt file for image-edit generation.")
    generation.add_argument("--sheet-size", default="512x1280", help="Generation size, default 512x1280.")
    generation.add_argument("--sheet-prefix", default="generated-sheet", help="Output filename prefix for generated sheet.")
    generation.add_argument(
        "--skip-generation-sheet",
        type=Path,
        default=None,
        help="Use an existing generated sheet instead of calling vg image edit.",
    )
    generation.add_argument("--quality", default="high", choices=["low", "medium", "high", "auto"])
    generation.add_argument("--background", default="opaque", choices=["opaque", "auto"])
    generation.add_argument(
        "--model",
        default="gpt-image-1.5",
        help="Model alias passed to vg image edit, default gpt-image-1.5.",
    )
    generation.add_argument(
        "--vg-bin",
        default="vg",
        help="Path or name of the vg CLI binary, default 'vg' on PATH.",
    )

    layout = parser.add_argument_group("Layout")
    layout.add_argument("--rows", type=int, required=True)
    layout.add_argument("--cols", type=int, required=True)
    layout.add_argument("--frame-canvas", default="256x256")
    layout.add_argument("--center-x", type=int, default=128)
    layout.add_argument("--bottom-y", type=int, default=255)
    layout.add_argument("--component-threshold", type=int, default=15)

    review = parser.add_argument_group("Review")
    review.add_argument("--selected-order", default="", help="Comma-separated selected frame order, e.g. 01,03,02,04,05")
    review.add_argument("--durations-ms", default="", help="Optional comma-separated durations matching selected-order.")
    review.add_argument("--flat-bg", default="#f0f0f0", help="Flat background for contact sheet and GIF previews.")
    review.add_argument("--label-prefix", default="F", help="Prefix for autogenerated labels, default F.")

    return parser.parse_args()


def require_generation_inputs(args: argparse.Namespace) -> None:
    if args.skip_generation_sheet is not None:
        return
    missing = [name for name in ["reference", "guide", "prompt_file"] if getattr(args, name) is None]
    if missing:
        raise SystemExit(f"Missing generation inputs: {', '.join(missing)}")


def main() -> None:
    args = parse_args()
    require_generation_inputs(args)

    work_dir = args.work_dir.resolve()
    work_dir.mkdir(parents=True, exist_ok=True)
    generated_dir = work_dir / "generated"
    recovered_dir = work_dir / "recovered-components"
    matte_dir = work_dir / "recovered-components-no-bg"
    normalized_dir = work_dir / "normalized-frames"
    review_dir = work_dir / "review"
    review_dir.mkdir(parents=True, exist_ok=True)
    generated_dir.mkdir(parents=True, exist_ok=True)

    if args.skip_generation_sheet is not None:
        sheet_path = args.skip_generation_sheet.resolve()
    else:
        prompt_text = args.prompt_file.read_text()
        params = {
            "size": args.sheet_size,
            "quality": args.quality,
            "background": args.background,
            "output_format": "png",
        }
        run(
            [
                args.vg_bin,
                "image",
                "edit",
                "--model",
                args.model,
                "--image",
                str(args.reference.resolve()),
                "--reference",
                str(args.guide.resolve()),
                "--prompt",
                prompt_text,
                "--output",
                str(generated_dir),
                "--filename-prefix",
                args.sheet_prefix,
                "--params",
                __import__("json").dumps(params),
            ]
        )
        generated = sorted(generated_dir.glob(f"{args.sheet_prefix}-*.png"))
        if not generated:
            raise SystemExit("Generation step completed without writing a sheet PNG.")
        sheet_path = generated[0]

    run(
        [
            "uv",
            "run",
            str(SCRIPTS_DIR / "recover_component_frames.py"),
            str(sheet_path),
            "--rows",
            str(args.rows),
            "--cols",
            str(args.cols),
            "--threshold",
            str(args.component_threshold),
            "--out-dir",
            str(recovered_dir),
            "--prefix",
            "frame",
        ]
    )

    _ = matte_dir
    recovery_source = recovered_dir
    recovery_glob = "frame-*.png"

    run(
        [
            "uv",
            "run",
            str(SCRIPTS_DIR / "normalize_frames.py"),
            "--input-dir",
            str(recovery_source),
            "--out-dir",
            str(normalized_dir),
            "--glob",
            recovery_glob,
            "--canvas",
            args.frame_canvas,
            "--center-x",
            str(args.center_x),
            "--bottom-y",
            str(args.bottom_y),
            "--flat-bg",
            args.flat_bg,
        ]
    )

    frame_files = sorted(normalized_dir.glob(recovery_glob))
    labels = [f"{args.label_prefix}{index:02d}" for index in range(1, len(frame_files) + 1)]
    labels_json = review_dir / "labels.json"
    labels_json.write_text(__import__("json").dumps(labels))

    run(
        [
            "uv",
            "run",
            str(SCRIPTS_DIR / "build_contact_sheet.py"),
            "--input-dir",
            str(normalized_dir),
            "--glob",
            recovery_glob,
            "--rows",
            str(args.rows),
            "--cols",
            str(args.cols),
            "--labels-json",
            str(labels_json),
            "--out",
            str(review_dir / "contact-sheet.png"),
            "--bg",
            args.flat_bg,
        ]
    )

    if args.selected_order:
        run(
            [
                "uv",
                "run",
                str(SCRIPTS_DIR / "build_sequence_gif.py"),
                "--input-dir",
                str(normalized_dir),
                "--pattern",
                recovery_glob.replace("*", "{id}"),
                "--order",
                args.selected_order,
                "--out",
                str(review_dir / "selected-sequence.gif"),
                "--flat-bg",
                args.flat_bg,
            ]
            + (
                ["--durations-ms", args.durations_ms]
                if args.durations_ms
                else []
            )
        )

    print("Pipeline complete.")
    print(f"Sheet: {sheet_path}")
    print(f"Recovered: {recovered_dir}")
    print(f"Normalized: {normalized_dir}")
    print(f"Review: {review_dir}")


if __name__ == "__main__":
    main()
