// Bake pier/dock polygons (OSM man_made=pier, fetched to sf-piers.raw.json)
// into src/world/sf-piers.ts. The Embarcadero finger piers + wharf docks are
// what makes SF's NE waterfront read as SF instead of a straight seawall.
//
//   node tools/sf-data/bake-piers.mjs

import { readFileSync, writeFileSync } from "node:fs";
import {
  onLandUV,
  rdp,
  ringArea,
  projU,
  projV,
  WORLD_H,
  WORLD_W,
} from "./lib.mjs";

const raw = JSON.parse(readFileSync(new URL("./sf-piers.raw.json", import.meta.url)));
const ways = raw.elements.filter((e) => e.type === "way" && e.geometry);
console.log(`pier ways: ${ways.length}`);

const closed = []; // { p: flat ring, area }
const open = []; // { p: flat polyline }
let landDrop = 0;
for (const w of ways) {
  const g = w.geometry;
  if (g.length < 2) continue;
  const isClosed = g[0].lat === g[g.length - 1].lat && g[0].lon === g[g.length - 1].lon;
  let pts = (isClosed ? g.slice(0, -1) : g).map((q) => {
    const u = projU(q.lon);
    const v = projV(q.lat);
    return [(u - 0.5) * WORLD_W, (v - 0.5) * WORLD_H];
  });
  // In-world bounds only.
  if (pts.some(([x, z]) => Math.abs(x) > WORLD_W / 2 || Math.abs(z) > WORLD_H / 2)) continue;
  // The game's traced coast sits seaward of the real shoreline along the
  // Embarcadero, which swallows exactly the finger piers that make the
  // waterfront read as SF. Land-locked piers SLIDE seaward along their own
  // long axis until they hang off the traced coast; only piers with no water
  // within reach are dropped.
  const waterAt = ([x, z]) => !onLandUV(x / WORLD_W + 0.5, z / WORLD_H + 0.5);
  const waterFrac = pts.filter(waterAt).length / pts.length;
  if (waterFrac < 0.35) {
    // Only substantial closed piers earn the slide — swallowed marina slips
    // and walkways just drop.
    if (!isClosed) {
      landDrop++;
      continue;
    }
    // Principal axis from the farthest-apart vertex pair (piers are long).
    let ax = 1;
    let az = 0;
    let bestD = 0;
    for (let i = 0; i < pts.length; i++) {
      for (let j = i + 1; j < pts.length; j++) {
        const dx = (pts[j][0] ?? 0) - (pts[i][0] ?? 0);
        const dz = (pts[j][1] ?? 0) - (pts[i][1] ?? 0);
        const d2 = dx * dx + dz * dz;
        if (d2 > bestD) {
          bestD = d2;
          ax = dx;
          az = dz;
        }
      }
    }
    const len = Math.sqrt(bestD) || 1;
    if (len < 15) {
      landDrop++;
      continue;
    }
    ax /= len;
    az /= len;
    let cx = 0;
    let cz = 0;
    for (const [x, z] of pts) {
      cx += x;
      cz += z;
    }
    cx /= pts.length;
    cz /= pts.length;
    // March both axis directions; the seaward one reaches water first.
    let shift = null;
    for (let d = 4; d <= 220; d += 4) {
      if (waterAt([cx + ax * d, cz + az * d])) {
        shift = [ax * (d + len * 0.28), az * (d + len * 0.28)];
        break;
      }
      if (waterAt([cx - ax * d, cz - az * d])) {
        shift = [-ax * (d + len * 0.28), -az * (d + len * 0.28)];
        break;
      }
    }
    if (!shift) {
      landDrop++;
      continue;
    }
    pts = pts.map(([x, z]) => [x + shift[0], z + shift[1]]);
    if (pts.some(([x, z]) => Math.abs(x) > WORLD_W / 2 || Math.abs(z) > WORLD_H / 2)) {
      landDrop++;
      continue;
    }
  }
  pts = rdp(pts, 0.25);
  if (isClosed && pts.length >= 3) {
    let ring = pts;
    if (ringArea(ring) < 0) ring = ring.reverse();
    const area = Math.abs(ringArea(ring));
    if (area < 8 || ring.length > 48) continue;
    closed.push({ p: ring.flat().map((n) => Math.round(n * 10) / 10), area });
  } else if (!isClosed && pts.length >= 2) {
    open.push({ p: pts.flat().map((n) => Math.round(n * 10) / 10) });
  }
}
closed.sort((a, b) => b.area - a.area);
console.log(`closed piers: ${closed.length}, open docks: ${open.length}, dropped on land: ${landDrop}`);

writeFileSync(
  new URL("../../src/world/sf-piers.ts", import.meta.url),
  `// AUTO-GENERATED by tools/sf-data/bake-piers.mjs — do not edit.
// Real pier/dock polygons (OSM man_made=pier), world units, water-clipped
// against the game's traced coast. Rendered by src/world/piers.ts.
export type PierPoly = { readonly p: readonly number[]; readonly area: number };

// Closed pier decks (CCW rings, [x0,z0,x1,z1,...]), largest first.
export const SF_PIERS: readonly PierPoly[] = [
${closed.map((c) => `  { p: [${c.p.join(",")}], area: ${Math.round(c.area)} },`).join("\n")}
];

// Open dock walkways (polylines).
export const SF_DOCKS: readonly (readonly number[])[] = [
${open.map((o) => `  [${o.p.join(",")}],`).join("\n")}
];
`,
);
console.log("Wrote src/world/sf-piers.ts");
