// Bake OSM landuse/leisure/natural polygons into per-cell ground classes:
// green (parks/grass/woods) and sand (beach). Ground color then follows
// reality instead of district boxes.  node tools/sf-data/bake-landuse.mjs

import { readFileSync, writeFileSync } from "node:fs";

const GRID_X = 244;
const GRID_Z = 200;
// Same calibrated projection as bake-network.mjs.
const U_M = 6.2462, U_B = 765.2557;
const V_M = -9.6095, V_B = 363.344;

const raw = JSON.parse(readFileSync(new URL("./sf-landuse.raw.json", import.meta.url)));
const green = new Uint8Array(GRID_X * GRID_Z);
const sand = new Uint8Array(GRID_X * GRID_Z);

const SAND_TAGS = new Set(["beach", "sand"]);

let polys = 0;
for (const e of raw.elements ?? []) {
  if (e.type !== "way" || !e.geometry || e.geometry.length < 3) continue;
  const isSand = SAND_TAGS.has(e.tags?.natural ?? "");
  const target = isSand ? sand : green;
  // Project ring to grid coords.
  const ring = e.geometry.map((g) => [
    (U_M * g.lon + U_B) * GRID_X,
    (V_M * g.lat + V_B) * GRID_Z,
  ]);
  let minX = Infinity, maxX = -Infinity, minZ = Infinity, maxZ = -Infinity;
  for (const [x, z] of ring) {
    minX = Math.min(minX, x); maxX = Math.max(maxX, x);
    minZ = Math.min(minZ, z); maxZ = Math.max(maxZ, z);
  }
  const gx0 = Math.max(0, Math.floor(minX));
  const gx1 = Math.min(GRID_X - 1, Math.ceil(maxX));
  const gz0 = Math.max(0, Math.floor(minZ));
  const gz1 = Math.min(GRID_Z - 1, Math.ceil(maxZ));
  if (gx1 < gx0 || gz1 < gz0) continue;
  polys++;
  for (let gx = gx0; gx <= gx1; gx++) {
    for (let gz = gz0; gz <= gz1; gz++) {
      // point-in-polygon at the cell centre
      const px = gx + 0.5;
      const pz = gz + 0.5;
      let inside = false;
      for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
        const [xi, zi] = ring[i];
        const [xj, zj] = ring[j];
        if (zi > pz !== zj > pz && px < ((xj - xi) * (pz - zi)) / (zj - zi) + xi) inside = !inside;
      }
      if (inside) target[gx * GRID_Z + gz] = 1;
    }
  }
}

const encode = (grid) => {
  const cols = [];
  for (let gx = 0; gx < GRID_X; gx++) {
    let bits = "";
    for (let gz = 0; gz < GRID_Z; gz++) bits += grid[gx * GRID_Z + gz] ? "1" : "0";
    let hex = "";
    for (let i = 0; i < bits.length; i += 4) {
      hex += parseInt(bits.slice(i, i + 4).padEnd(4, "0"), 2).toString(16);
    }
    cols.push(hex);
  }
  return cols;
};

let greenCells = 0;
let sandCells = 0;
for (let i = 0; i < green.length; i++) {
  if (green[i]) greenCells++;
  if (sand[i]) sandCells++;
}
console.log(`${polys} polygons -> green ${greenCells} cells, sand ${sandCells} cells`);

writeFileSync(
  new URL("../../src/world/sf-landuse.ts", import.meta.url),
  `// AUTO-GENERATED by tools/sf-data/bake-landuse.mjs — do not edit by hand.
// Real OSM landuse: green (parks/grass/woods) + sand (beach) per grid cell.
const GREEN_COLS = ${JSON.stringify(encode(green))} as const;
const SAND_COLS = ${JSON.stringify(encode(sand))} as const;

function bit(cols: readonly string[], gx: number, gz: number): boolean {
  const col = cols[gx];
  if (col === undefined || gz < 0) return false;
  const nibble = col.charCodeAt(gz >> 2);
  const val = nibble <= 57 ? nibble - 48 : nibble - 87;
  return (val & (8 >> (gz & 3))) !== 0;
}

export function landuseGreenAt(gx: number, gz: number): boolean {
  return bit(GREEN_COLS, gx, gz);
}
export function landuseSandAt(gx: number, gz: number): boolean {
  return bit(SAND_COLS, gx, gz);
}
`,
);
console.log("sf-landuse.ts written");
